/*******************************************************************************
 * File Name: project.h  
 * PSoC Creator 2.2 Service Pack 1
 *
 *  Description:
 *  This file is automatically generated by PSoC Creator and should not 
 *  be edited by hand.
 *
 *
 ********************************************************************************
 * Copyright 2008-2013, Cypress Semiconductor Corporation.  All rights reserved.
 * You may use this file only in accordance with the license, terms, conditions, 
 * disclaimers, and limitations in the end user license agreement accompanying 
 * the software package with which this file was provided.
 ********************************************************************************/

#include <cyfitter_cfg.h>
#include <cydevice.h>
#include <cydevice_trm.h>
#include <cyfitter.h>
#include <I2C.h>
#include <I2C_PVT.h>
#include <SDA_aliases.h>
#include <SDA.h>
#include <SCL_aliases.h>
#include <SCL.h>
#include <LED_1_aliases.h>
#include <LED_1.h>
#include <LED_Out.h>
#include <LED_2_aliases.h>
#include <LED_2.h>
#include <I2C_IntClock.h>
#include <core_cm3_psoc5.h>
#include <core_cm3.h>
#include <CyDmac.h>
#include <CyFlash.h>
#include <CyLib.h>
#include <cypins.h>
#include <cyPm.h>
#include <CySpc.h>
#include <cytypes.h>

/*[]*/

